// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAio3R73oZtCmR0B9BTQA5FmnCxKZYaEbc',
    appId: '1:828486672867:web:6cd53678afc6083739c0d6',
    messagingSenderId: '828486672867',
    projectId: 'flutter-firebase-c1e1d',
    authDomain: 'flutter-firebase-c1e1d.firebaseapp.com',
    storageBucket: 'flutter-firebase-c1e1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnkjiXK9RSMaC4n-7J-ytvXO4AX3ZEPXU',
    appId: '1:828486672867:android:28e63d1a23b907ed39c0d6',
    messagingSenderId: '828486672867',
    projectId: 'flutter-firebase-c1e1d',
    storageBucket: 'flutter-firebase-c1e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zt6O8PP13d7Bn9_jsv20aqE-Hu8GIsQ',
    appId: '1:828486672867:ios:8e9e2774ed3484f539c0d6',
    messagingSenderId: '828486672867',
    projectId: 'flutter-firebase-c1e1d',
    storageBucket: 'flutter-firebase-c1e1d.appspot.com',
    iosBundleId: 'com.mochamaddarmawanh.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2zt6O8PP13d7Bn9_jsv20aqE-Hu8GIsQ',
    appId: '1:828486672867:ios:8e9e2774ed3484f539c0d6',
    messagingSenderId: '828486672867',
    projectId: 'flutter-firebase-c1e1d',
    storageBucket: 'flutter-firebase-c1e1d.appspot.com',
    iosBundleId: 'com.mochamaddarmawanh.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAio3R73oZtCmR0B9BTQA5FmnCxKZYaEbc',
    appId: '1:828486672867:web:34b7a445519cbd5939c0d6',
    messagingSenderId: '828486672867',
    projectId: 'flutter-firebase-c1e1d',
    authDomain: 'flutter-firebase-c1e1d.firebaseapp.com',
    storageBucket: 'flutter-firebase-c1e1d.appspot.com',
  );
}
